HRMS/Controllers/OrganisationController.cs
using HRMS.Entity.Models;
using HRMS.Services.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;

namespace HRMS.Controllers
{
    [Authorize]
    public class OrganisationController : Controller
    {
        private readonly iOrganisationRepository _repository;
        private readonly ApplicationDbContext _context;

        public OrganisationController(iOrganisationRepository repository, ApplicationDbContext context)
        {
            _repository = repository;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        //-----------------------------------------------------------------------------------------------
        public async Task<IActionResult> CreatePosition()
        {
            Position pos = new Position(); ;
            return View(pos);
        }
        [HttpPost]
        public async Task<IActionResult> CreatePosition(Position pos)
        {
            if (ModelState.IsValid)
            {
                await _repository.AddPosition(pos);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditPosition(int id)
        {
            var pos = await _repository.GetPositionById(id);
            return View(pos);
        }
        [HttpPost]
        public async Task<IActionResult> EditPosition(Position pos)
        {
            if (ModelState.IsValid)
            {
                await _repository.UpdatePosition(pos);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeletePosition(int id)
        {
            var pos = await _repository.GetPositionById(id);
            return View(pos);
        }
        [HttpPost]
        [ActionName("DeletePosition")]
        public async Task<IActionResult> ConfrimDeletePosition(int id)
        {
            await _repository.DeletePosition(id);
            return RedirectToAction("Index");
        }

        //------------------------------------------------------------------------------------------------

        public async Task<IActionResult> CreateDepartment()
        {
            Department dept = new Department(); ;
            return View(dept);
        }
        [HttpPost]
        public async Task<IActionResult> CreateDepartment(Department dept)
        {
            if (ModelState.IsValid)
            {
                await _repository.AddDepartment(dept);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditDepartment(int id)
        {
            var dept = await _repository.GetDepartmentById(id);
            return View(dept);
        }
        [HttpPost]
        public async Task<IActionResult> EditDepartment(Department dept)
        {
            if (ModelState.IsValid)
            {
                await _repository.UpdateDepartment(dept);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteDepartment(int id)
        {
            var dept = await _repository.GetDepartmentById(id);
            return View(dept);
        }
        [HttpPost]
        [ActionName("DeleteDepartment")]
        public async Task<IActionResult> ConfrimDeleteDepartment(int id)
        {
            await _repository.DeleteDepartment(id);
            return RedirectToAction("Index");
        }

        //------------------------------------------------------------------------------------------------

        public async Task<IActionResult> CreateLocation()
        {
            Location loc = new Location(); ;
            return View(loc);
        }
        [HttpPost]
        public async Task<IActionResult> CreateLocation(Location loc)
        {
            if (ModelState.IsValid)
            {
                await _repository.AddLocation(loc);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditLocation(int id)
        {
            var loc = await _repository.GetLocationById(id);
            return View(loc);
        }
        [HttpPost]
        public async Task<IActionResult> EditLocation(Location loc)
        {
            if (ModelState.IsValid)
            {
                await _repository.UpdateLocation(loc);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteLocation(int id)
        {
            var loc = await _repository.GetLocationById(id);
            return View(loc);
        }
        [HttpPost]
        [ActionName("DeleteLocation")]
        public async Task<IActionResult> ConfrimDeleteLocation(int id)
        {
            await _repository.DeleteLocation(id);
            return RedirectToAction("Index");
        }

        //----------------------------------------------------------------------------------------------
        public async Task<JsonResult> getJsonPosition()
        {
            var pos = _context.Positions.GroupJoin(_context.EmployeeDetails,
                p => p.positionId,
                e => e.positionId,
                (position, employees) => new
                    {
                        positionName = position.positionName,
                        id=position.positionId,
                        empCount = employees.Count()
                    }).ToList();

            return Json(new { data = pos });
        }

        public async Task<JsonResult> getJsonDepartment()
        {
            var dept = _context.Departments.GroupJoin(_context.EmployeeDetails,
                d => d.departmentId,
                e => e.deptId,
                (department, employees) => new
                {
                    departmentName = department.departmentName,
                    id = department.departmentId,
                    empCount = employees.Count()
                }).ToList();
            return Json(new { data = dept });
        }

        public async Task<JsonResult> getJsonLocation()
        {
            var loc = _context.Locations.GroupJoin(_context.EmployeeDetails,
                l => l.locationId,
                e => e.locationId,
                (locations, employees) => new
                {
                    locationName = locations.location,
                    id= locations.locationId,
                    empCount = employees.Count()
                }).ToList();
            return Json(new { data = loc });
        }
    }
}

HRMS/Views/Organisation/CreateDepartment.cshtml
@model HRMS.Entity.Models.Department

@{
    Layout = "_NoNavLayout";
}

<div class="row" style="text-align:center">
    <div class="col-md-12">
        <form asp-action="CreateDepartment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="departmentName" class="control-label">Department</label>
                <input asp-for="departmentName" class="form-control" />
                <span asp-validation-for="departmentName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input  type="submit" value="Add Department" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HRMS/Views/Organisation/CreateLocation.cshtml
@model HRMS.Entity.Models.Location

@{
    Layout = "_NoNavLayout";
}


<div class="row" style="text-align:center">
    <div class="col-md-12">
        <form asp-action="CreateLocation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="location" class="control-label">Location</label>
                <input asp-for="location" class="form-control" />
                <span asp-validation-for="location" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Add Location" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HRMS/Views/Organisation/CreatePosition.cshtml
@model HRMS.Entity.Models.Position

@{
    Layout = "_NoNavLayout";
}


<div class="row" style="text-align:center">
    <div class="col-md-12">
        <form asp-action="CreatePosition">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
       
            <div class="form-group">
                <label asp-for="positionName" class="control-label">Position</label>
                <input asp-for="positionName" class="form-control" />
                <span asp-validation-for="positionName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Add Position" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HRMS/Views/Organisation/Index.cshtml
<title>
    Organisation
</title>

@{
    bool flag = false;
    if (User.IsInRole("Admin"))
    {
        flag = true;
    }
}

<!-- Dept Modal -->
<div class="modal fade" id="deptModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title card-title" style="padding:0">Add Department</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="deptModalContent">
                
            </div>
        </div>
    </div>
</div>

<!-- Pos Modal -->
<div class="modal fade" id="posModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title card-title" style="padding:0">Add Position</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="posModalContent">
            </div>
        </div>
    </div>
</div>

<!-- Loc Modal -->
<div class="modal fade" id="locModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered ">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title card-title" style="padding:0">Add Location</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="locModalContent">
            </div>
        </div>
    </div>
</div>


<body>
    <div class="pagetitle">
        <h1>Organisation</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Home</li>
                <li class="breadcrumb-item active">Organisation</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-12">
                <div class="row">

                    <!-- Department Card -->
                    <div class="col-4">
                        <div class="card info-card sales-card">
                            <div class="card-body">
                                <h5 class="card-title">Departments <span>| Employees</span> 
                                    @if (flag == true)
                                    {
                                        <a id="addDept" style="float:right" href="#" class="btn btn-sm btn-outline-success">+</a>
                                    }
                                    </h5>
                                    <table style="text-align:center;width:100%" id="deptTab" class="table table-striped table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th>Department</th>
                                                <th>Count</th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                            </div>
                        </div>
                    </div><!-- End Dept Card -->

                    <!-- Positions Card -->
                    <div class="col-4">
                        <div class="card info-card sales-card">
                            <div class="card-body">
                                <h5 class="card-title">Positions <span>| Employees</span>
                                    @if (flag == true)
                                    {
                                        <a style="float:right" id="addPos" href="#" class="btn btn-sm btn-outline-success">+</a>
                                    }
                                </h5>
                                
                                    <table style="text-align:center;width:100%" id="posTab" class="table table-striped table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th>Position</th>
                                                <th>Count</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                          
                                        </tbody>
                                    </table>
                                
                            </div>
                        </div>
                    </div><!-- End Leave Card -->

                    <div class="col-4">
                        <div class="card info-card sales-card">
                            <div class="card-body">
                                <h5 class="card-title">Locations <span>| Employees</span>
                                    @if (flag == true)
                                    {
                                        <a style="float:right" id="addLoc" href="#" class="btn btn-sm btn-outline-success">+</a>
                                    }
                                </h5>
                                    <table style="text-align:center;width:100%" id="locTab" class="table table-striped table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th>Location</th>
                                                <th>Count</th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>

                                    </table>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div><!-- End Left side columns -->
            

        </div>
    </section>

</body>

@section scripts{
    <link href="~/lib/datatables/css/datatables.bootstrap.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/datatables/js/jquery.datatables.js"></script>
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#deptTab").DataTable(
                {
                    "processing": false,
                    "serverSide": false,
                    "filter": false,
                    "paging": false,  // Disable pagination
                    "bLengthChange": false,
                    "language": {
                        "info": ""  // Set the info option to an empty string to hide the message
                    },
                    "ajax": {
                        "url": '@Url.Action("getJsonDepartment","Organisation")',
                        "type": "GET",
                        "datatype": "json"
                    },
                    "columnDefs": [{
                        "targets": [0],
                        "visible": true,
                        "searchable": false
                    }],
                    "columns": [
                        { "data": "departmentName", "name": "Department", "autoWidth": true },
                        { "data": "empCount", "name": "Count", "autoWidth": true },
                    ]
                });

            $("#posTab").DataTable(
                {
                    "processing": false,
                    "serverSide": false,
                    "filter": false,
                    "paging": false,  // Disable pagination
                    "bLengthChange": false,
                    "language": {
                        "info": ""  // Set the info option to an empty string to hide the message
                    },
                    "ajax": {
                        "url": '@Url.Action("getJsonPosition","Organisation")',
                        "type": "GET",
                        "datatype": "json"
                    },
                    "columnDefs": [{
                        "targets": [0],
                        "visible": true,
                        "searchable": false
                    }],
                    "columns": [
                        { "data": "positionName", "name": "Position", "autoWidth": true },
                        { "data": "empCount", "name": "Count", "autoWidth": true },
                    ]
                });

            $("#locTab").DataTable(
                {
                    "processing": false,
                    "serverSide": false,
                    "filter": false,
                    "paging": false,  // Disable pagination
                    "bLengthChange": false,
                    "language": {
                        "info": "" ,// Set the info option to an empty string to hide the message
                    },
                    "ajax": {
                        "url": '@Url.Action("getJsonLocation","Organisation")',
                        "type": "GET",
                        "datatype": "json"
                    },
                    "columnDefs": [{
                        "targets": [0],
                        "visible": true,
                        "searchable": false
                    }],
                    "columns": [
                        { "data": "locationName", "name": "Location", "autoWidth": true },
                        { "data": "empCount", "name": "Count", "autoWidth": true },
                    ]
                });
        });

        $('#addDept').click(function () {
            $.ajax({
                type: "GET",
                url: '@Url.Action("CreateDepartment", "Organisation")',
                contentType: false,
                processData: false,
                success: function (data) {
                    $("#deptModalContent").html(data);
                    $("#deptModal").modal('show');
                },
                error: function () {
                    alert("Load Failed! Please contact your administrator.");
                }
            });
        });

        $('#addPos').click(function () {
            $.ajax({
                type: "GET",
                url: '@Url.Action("CreatePosition", "Organisation")',
                contentType: false,
                processData: false,
                success: function (data) {
                    $("#posModalContent").html(data);
                    $("#posModal").modal('show');
                },
                error: function () {
                    alert("Load Failed! Please contact your administrator.");
                }
            });
        });

        $('#addLoc').click(function () {
            $.ajax({
                type: "GET",
                url: '@Url.Action("CreateLocation", "Organisation")',
                contentType: false,
                processData: false,
                success: function (data) {
                    $("#locModalContent").html(data);
                    $("#locModal").modal('show');
                },
                error: function () {
                    alert("Load Failed! Please contact your administrator.");
                }
            });
        });
    </script>
}