HRMS/Controllers/EmployeeController.cs
using HRMS.Entity.Models;
using HRMS.Entity.ViewModels;
using HRMS.Services.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Controllers
{
    [Authorize(Roles = "Admin")]

    public class EmployeeController : Controller
    {
        private readonly iOrganisationRepository _orgRepository;
        private readonly iEmployeeRepository _repository;
        private readonly IWebHostEnvironment _env;

        public EmployeeController(iOrganisationRepository orgRepository, iEmployeeRepository repository, IWebHostEnvironment env)
        {
            _orgRepository = orgRepository;
            _repository = repository;
            _env = env;
        }
        public IActionResult Index()
        {
            var emp = new List<EmployeeDetail>();
            return View(emp);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.positions = await _orgRepository.GetPositions();
            ViewBag.departments = await _orgRepository.GetDepartments();
            ViewBag.locations = await _orgRepository.GetLocations();
            ViewBag.emp = await _repository.GetAllEmployees();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string firstName, string lastName, string midName,
           int positionId, int deptId, int locationId, DateTime birthDate, int age, string sex, string address,
           int supervisorId/*, IFormFile filepath*/)
        {
            EmployeeDetail emp = new EmployeeDetail();
            emp.firstName = firstName;
            emp.lastName = lastName;
            emp.midName = midName;
            emp.positionId = positionId;
            emp.deptId = deptId;
            emp.locationId = locationId;
            emp.birthDate = birthDate;
            emp.age = age;
            emp.sex = sex;
            emp.address = address;
            emp.employedDate = DateTime.Now;
            emp.supervisorId = supervisorId;
            //emp.filepath = filepath;

            //string fullPath = string.Empty;
            //if (emp.filepath != null)
            //{
            //    var imagePath = Path.Combine(_env.WebRootPath, "Images");
            //    string filename = emp.firstName + emp.filepath.FileName;
            //    fullPath = Path.Combine(imagePath, filename);
            //    if (!System.IO.File.Exists(fullPath))
            //    {
            //        emp.filepath.CopyTo(new FileStream(fullPath, FileMode.Create));
            //    }
            //    emp.image = filename;
            //}

            await _repository.AddEmployee(emp);

            return Ok(emp.empId);
        }



        //public async Task<IActionResult> Edit(int id)
        //{
        //    var customer = await _repository.GetCustomerById(id);
        //    var category = await _repository.GetCategory();
        //    ViewBag.category = category;
        //    return View(customer);
        //}

        //[HttpPost]
        //[Authorize(Policy = "EditPolicy")]

        //public async Task<IActionResult> Edit(Customer cus)
        //{
        //    string fullPath = string.Empty;

        //    if (cus.filepath != null)
        //    {
        //        var imagePath = Path.Combine(_env.WebRootPath, "Images");
        //        string filename = cus.firstName + cus.filepath.FileName;
        //        fullPath = Path.Combine(imagePath, filename);
        //        if (!System.IO.File.Exists(fullPath))
        //        {
        //            cus.filepath.CopyTo(new FileStream(fullPath, FileMode.Create));
        //        }
        //        cus.image = filename;
        //    }
        //    if (ModelState.IsValid)
        //    {
        //        await _repository.UpdateCustomer(cus);
        //    }
        //    return RedirectToAction("Index");
        //}

        //[Authorize(Policy = "DeletePolicy")]

        //public async Task<IActionResult> Delete(int id)
        //{
        //    var customer = await _repository.GetCustomerById(id);
        //    return View(customer);
        //}

        //[HttpPost]
        //[ActionName("Delete")]
        //[Authorize(Policy = "DeletePolicy")]
        //public async Task<IActionResult> ConfrimDelete(int id)
        //{
        //    //var customer = _repository.GetCustomerById(id);
        //    await _repository.DeleteCustomerById(id);
        //    return RedirectToAction("Index");
        //}

        //public async Task<IActionResult> Details(int id)
        //{
        //    var customer = await _repository.GetCustomerById(id);
        //    return View(customer);
        //}

        public async Task<JsonResult> getJsonEmployee()
        {
            var emp = await _repository.GetDetailedEmployees();
            return Json(new { data = emp });
        }

        public async Task<IActionResult> Details(int id)
        {
            var emp = await _repository.GetDetailedEmployeeById(id);
            return View(emp);
        }
    }
}

HRMS/Controllers/LeaveController.cs
using HRMS.Entity.Models;
using HRMS.Services.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;

namespace HRMS.Controllers
{
    [Authorize]

    public class LeaveController : Controller
    {
        private readonly iLeaveRepository _repository;

        public LeaveController(iLeaveRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Attendance()
        {
            return View();
        }

        public async Task<IActionResult> ListLeaves()
        {
            List<Leave> leaves = new();
            leaves = await _repository.GetLeaveTypes();
            return View(leaves);
        }

        public async Task<IActionResult> ApplyLeave()
        {
            ViewBag.leaves = await _repository.GetLeaveTypes();
            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> ApplyLeave(EmployeeLeave leave)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        await _repository.AddProduct(product);
        //    }
        //    return RedirectToAction("Index");
        //}
    }
}

HRMS/Controllers/SalaryController.cs
using HRMS.Entity.Models;
using HRMS.Entity.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using NuGet.Protocol.Core.Types;

namespace HRMS.Controllers
{
    [Authorize]
    public class SalaryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;
        private readonly IToastNotification _toast;

        public SalaryController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IToastNotification toast)
        {
            _context = context;
            _userManager = userManager;
            _toast = toast;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var empId = user.EmployeeId;
            var sal = _context.EmployeeSalaries.FirstOrDefault(e => e.empId == empId);
            return View(sal);
        }


        [HttpPost]
        public async Task<IActionResult> Create(float annualIncome, float taxable, float pfCuts, int empId)
        {
            EmployeeSalary sal = new EmployeeSalary();
            sal.empId = empId;
            sal.taxable = taxable;
            sal.annualIncome = annualIncome;
            sal.pfCuts = pfCuts;

            if (ModelState.IsValid)
            {
                await _context.EmployeeSalaries.AddAsync(sal);
                await _context.SaveChangesAsync();
                _toast.AddSuccessToastMessage("Employee Registered!");

            }
            return NoContent();
        }

        //public async Task<IActionResult> EditPosition(int id)
        //{
        //    var pos = await _repository.GetPositionById(id);
        //    return View(pos);
        //}
        //[HttpPost]
        //public async Task<IActionResult> EditPosition(Position pos)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        await _repository.UpdatePosition(pos);
        //    }
        //    return RedirectToAction("Index");
        //}

        //public async Task<IActionResult> DeletePosition(int id)
        //{
        //    var pos = await _repository.GetPositionById(id);
        //    return View(pos);
        //}
        //[HttpPost]
        //[ActionName("DeletePosition")]
        //public async Task<IActionResult> ConfrimDeletePosition(int id)
        //{
        //    await _repository.DeletePosition(id);
        //    return RedirectToAction("Index");
        //}
    }
}

HRMS/Controllers/WorkController.cs
using HRMS.Entity.Models;
using HRMS.Entity.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;

namespace HRMS.Controllers
{
    [Authorize]
    public class WorkController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public WorkController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }
        public async Task<IActionResult> Index()
        {
            var proj = new List<EmployeeProject>();
            proj = await _context.EmployeeProjects.Include(p => p.project).ToListAsync();
            ViewBag.projects = proj;
            var tr = new List<EmployeeTraining>();
            tr = await _context.EmployeeTrainings.Include(t => t.training).ToListAsync();
            ViewBag.trainings = tr;
            var user = await _userManager.GetUserAsync(User);
            ViewBag.userId = user.EmployeeId;
            return View();
        }

        public async Task<IActionResult> CreateProject()
        {
            Project project = new Project(); 
            return View(project);
        }
        [HttpPost]
        public async Task<IActionResult> CreateProject(Project pos)
        {
            if (ModelState.IsValid)
            {
                _context.Projects.AddAsync(pos);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> CreateTraining()
        {
            Training training = new Training(); 
            return View(training);
        }
        [HttpPost]
        public async Task<IActionResult> CreateTraining(Training t)
        {
            if (ModelState.IsValid)
            {
                _context.Trainings.AddAsync(t);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AssignProject()
        {
            EmployeeProject project = new EmployeeProject();
            var employees = await _context.EmployeeDetails.ToListAsync();
            var projects = await _context.Projects.ToListAsync();
            ViewBag.projects = projects;
            ViewBag.employees = employees;
            return View(project);
        }
        [HttpPost]
        public async Task<IActionResult> AssignProject(EmployeeProject pos)
        {
           
                _context.EmployeeProjects.AddAsync(pos);
                await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
    }
}

HRMS/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    @* <title>Unity</title> *@
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <!-- Logo -->
        <div class="d-flex align-items-center justify-content-between">
            <a asp-action="Index" asp-controller="Home" class="logo d-flex align-items-center">
                <img src="~/assets/img/logo.png" style="width:50px" alt="">
                <span class="d-none d-lg-block"> HRMS</span> 
            </a>
            @* <i class="bi bi-list toggle-sidebar-btn"></i> *@
        </div>

        <!-- Search Bar -->
     @*    <div class="search-bar ">
            <form class="search-form d-flex justify-content-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div> *@

        <!-- Navigation Bar -->
        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <!-- Profile Dropdown -->
                <li class="nav-item dropdown pe-3">

                    <!-- Profile Image Icon -->
                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">@User.Identity.Name</span>
                    </a>

                    <!-- Profile Dropdown Items -->
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>@User.Identity.Name</h6>
                            @* <span>Administrator</span> *@
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" asp-action="ViewProfile" asp-controller="Account">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center"  asp-action="SignOut" asp-controller="Account">
                                <i class="bi bi-box-arrow-right" style="color:red"></i>
                                <span style="-webkit-text-fill-color:red">Sign Out</span>
                            </a>
                        </li>

                    </ul>
                </li><!-- End Profile Nav -->
            </ul>
        </nav><!-- End Icons Navigation -->
    </header>

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar" onmouseover="expandSidebar()" onmouseout="collapseSidebar()">

        <ul class="sidebar-nav" id="sidebar-nav">

            <!-- Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" id="dashboard" asp-action="Index" asp-controller="Home">
                    <i class="bi bi-grid" style="margin-right: 12px;"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Attendance -->
            <li class="nav-item">
                <a class="nav-link collapsed" id="attendance" asp-action="Attendance" asp-controller="Leave">
                    <i class="bi bi-calendar-check" style="margin-right: 12px;"></i>
                    <span>Attendance</span>
                </a>
            </li>

            <!-- Leave -->
            <li class="nav-item">
                <a class="nav-link collapsed" id="leave" asp-action="ListLeaves" asp-controller="Leave">
                    <i class="bi bi-calendar-minus" style="margin-right: 12px;"></i>
                    <span>Leaves</span>
                </a>
            </li>

            <!-- Work -->
            <li class="nav-item">
                <a class="nav-link collapsed" id="work" asp-action="Index" asp-controller="Work">
                    <i class="bi bi-suitcase-lg" style="margin-right: 12px;"></i>
                    <span>Work</span>
                </a>
            </li>

            <!-- Organization -->
            <li class="nav-item">
                <a class="nav-link collapsed" id="organisation" asp-action="Index" asp-controller="Organisation">
                    <i class="bi bi-building" style="margin-right: 12px;"></i>
                    <span>Organisation</span>
                </a>
            </li>

            <!-- Salary -->
            <li class="nav-item">
                <a class="nav-link collapsed" id="salary" asp-action="Index" asp-controller="Salary">
                    <i class="bi bi-wallet2" style="margin-right: 12px;"></i>
                    <span>MyPay</span>
                </a>
            </li>

            <!-- News -->
            <li class="nav-item">
                <a class="nav-link collapsed" id="news" asp-action="Index" asp-controller="News">
                    <i class="bi bi-newspaper" style="margin-right: 12px;"></i>
                    <span>News</span>
                </a>
            </li>
            @if (User.IsInRole("Admin"))
            {
            <!-- Manage Emplolyees -->
            <li class="nav-item">
                <a class="nav-link collapsed" asp-action="Index" asp-controller="Employee">
                    <i class="bi bi-people" style="margin-right: 12px;"></i>
                    <span>Manage Employees</span>
                </a>
            </li>
            }
         

            <!-- Blank -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="pages-register.html">
                    <span></span>
                </a>
            </li>

            <!-- Sign Out -->
            <li class="nav-item">
                <a class="nav-link collapsed" asp-action="SignOut" asp-controller="Account">
                    <i class="bi bi-box-arrow-right" style="margin-right: 12px;"></i>
                    <span style="color:darkred">Sign Out</span>
                </a>
            </li>

        </ul>

    </aside><!-- End Sidebar-->

    <main id="main" class="main">
        @RenderBody()
    </main><!-- End #main -->

@*     <footer id="footer" class="footer">
        <div class="credits">
            Designed by <i>Pranav Sudhir</i>
        </div>
    </footer><!-- End Footer --> *@

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.min.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <!-- Template Main JS File -->
    <script>
        function expandSidebar() {
            console.log("opening sidebar");
            document.getElementById("sidebar").style.width = "200px";
            document.getElementById("main").style.marginLeft = "250px";
        }
        function collapseSidebar() {
            console.log("closing sidebar");
            document.getElementById("sidebar").style.width = "30px";
            document.getElementById("main").style.marginLeft = "50px";
        }
    </script>

    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>
@* @section scripts{
    <script>
        $(document).ready(function () {
            collapseSidebar();
        });
    </script>
           
} *@


HRMS/Views/Shared/_NoNavLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    @* <title>Unity</title> *@
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>
<body>
    <header>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.min.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
